In [111]:
from __future__ import division
from utils import *
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from functools import partial
%matplotlib inline

In [119]:
def lret(x): 
    x = x - x.mean()
    return logreturn(x, x.shift(1))

def macross(x, lw,sw):
    ret = lret(x)
    l = ret.ewm(lw).mean()
    s = ret.ewm(sw).mean()
    return (s > l) * 1

In [275]:
def load_data():   
    feature_defs = {}
    for s in [2,4,8,16,32,64]:
        l = 2*s
        feature_defs['ma_{}_{}'.format(l,s)] = lambda x:macross(x,l,s)    
    
    features_and_targets = partial(
        create_features_and_targets,
        feature_defs=feature_defs,
        target_defs={'up': lambda x:  (lret(x.shift(-1)) > 0)*1 }
    )
    return load_stock_datasets(features_and_targets)

In [ ]:
data = load_data()
ds = concatenate_datasets(data)

In [277]:
print preview(ds.X_train, ds.Y_train)
print preview(ds.X_train.describe(),ds.Y_train.describe(), n=100)

from sklearn.metrics import confusion_matrix

print -100 + 400*confusion_matrix(ds.Y_train, ds.X_train.ma_4_2)/len(ds.Y_train)
print -100 + 400*confusion_matrix(ds.Y_train, ds.X_train.ma_8_4)/len(ds.Y_train)
print -100 + 400*confusion_matrix(ds.Y_train, ds.X_train.ma_16_8)/len(ds.Y_train)
print -100 + 400*confusion_matrix(ds.Y_train, ds.X_train.ma_32_16)/len(ds.Y_train)
print -100 + 400*confusion_matrix(ds.Y_train, ds.X_train.ma_64_32)/len(ds.Y_train)
print -100 + 400*confusion_matrix(ds.Y_train, ds.X_train.ma_128_64)/len(ds.Y_train)

print np.corrcoef(ds.Y_train.values.ravel(), ds.X_train.ma_4_2.values.ravel())
print np.corrcoef(ds.Y_train.values.ravel(), ds.X_train.ma_8_4.values.ravel())
print np.corrcoef(ds.Y_train.values.ravel(), ds.X_train.ma_16_8.values.ravel())
print np.corrcoef(ds.Y_train.values.ravel(), ds.X_train.ma_32_16.values.ravel())
print np.corrcoef(ds.Y_train.values.ravel(), ds.X_train.ma_64_32.values.ravel())
print np.corrcoef(ds.Y_train.values.ravel(), ds.X_train.ma_128_64.values.ravel())

   ma_4_2  ma_256_128  ma_8_4  ma_32_16  ma_16_8  ma_128_64  ma_64_32  up
0       0           0       0         0        0          0         0   0
1       0           0       0         0        0          0         0   1
2       0           0       0         0        0          0         0   1
3       0           0       0         0        0          0         0   0
              ma_4_2     ma_256_128         ma_8_4       ma_32_16  \
count  380955.000000  380955.000000  380955.000000  380955.000000
mean        0.438540       0.438540       0.438540       0.438540
std         0.496209       0.496209       0.496209       0.496209
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         1.000000       1.000000       1.000000       1.000000
max         1.000000       1.000000       1.000000       1.000000

             ma_16_8      ma_128_64       ma_64_32             up
count  380955.000000  380955.000000  380955.000000  380955.000000
mean        0.438540       0.438540       0.438540       0.474366
std         0.496209       0.496209       0.496209       0.499343
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         1.000000       1.000000       1.000000       1.000000
max         1.000000       1.000000       1.000000       1.000000
[[ 17.81654001  -7.56283551]
 [  6.76746597 -17.02117048]]
[[ 17.81654001  -7.56283551]
 [  6.76746597 -17.02117048]]
[[ 17.81654001  -7.56283551]
 [  6.76746597 -17.02117048]]
[[ 17.81654001  -7.56283551]
 [  6.76746597 -17.02117048]]
[[ 17.81654001  -7.56283551]
 [  6.76746597 -17.02117048]]
[[ 17.81654001  -7.56283551]
 [  6.76746597 -17.02117048]]
[[ 1.         -0.00234593]
 [-0.00234593  1.        ]]
[[ 1.         -0.00234593]
 [-0.00234593  1.        ]]
[[ 1.         -0.00234593]
 [-0.00234593  1.        ]]
[[ 1.         -0.00234593]
 [-0.00234593  1.        ]]
[[ 1.         -0.00234593]
 [-0.00234593  1.        ]]
[[ 1.         -0.00234593]
 [-0.00234593  1.        ]]

In [278]:
ds.X_train

      ma_4_2  ma_256_128  ma_8_4  ma_32_16  ma_16_8  ma_128_64  ma_64_32
0          0           0       0         0        0          0         0
1          0           0       0         0        0          0         0
2          0           0       0         0        0          0         0
3          0           0       0         0        0          0         0
4          0           0       0         0        0          0         0
5          0           0       0         0        0          0         0
6          0           0       0         0        0          0         0
7          0           0       0         0        0          0         0
8          0           0       0         0        0          0         0
9          0           0       0         0        0          0         0
10         0           0       0         0        0          0         0
11         0           0       0         0        0          0         0
12         0           0       0         0        0          0         0
13         0           0       0         0        0          0         0
14         0           0       0         0        0          0         0
15         0           0       0         0        0          0         0
16         0           0       0         0        0          0         0
17         0           0       0         0        0          0         0
18         0           0       0         0        0          0         0
19         0           0       0         0        0          0         0
20         0           0       0         0        0          0         0
21         0           0       0         0        0          0         0
22         0           0       0         0        0          0         0
23         0           0       0         0        0          0         0
24         0           0       0         0        0          0         0
25         0           0       0         0        0          0         0
26         0           0       0         0        0          0         0
27         0           0       0         0        0          0         0
28         0           0       0         0        0          0         0
29         0           0       0         0        0          0         0
...      ...         ...     ...       ...      ...        ...       ...
4785       1           1       1         1        1          1         1
4786       1           1       1         1        1          1         1
4787       1           1       1         1        1          1         1
4788       1           1       1         1        1          1         1
4789       1           1       1         1        1          1         1
4790       1           1       1         1        1          1         1
4791       1           1       1         1        1          1         1
4792       1           1       1         1        1          1         1
4793       1           1       1         1        1          1         1
4794       1           1       1         1        1          1         1
4795       1           1       1         1        1          1         1
4796       1           1       1         1        1          1         1
4797       0           0       0         0        0          0         0
4798       0           0       0         0        0          0         0
4799       0           0       0         0        0          0         0
4800       0           0       0         0        0          0         0
4801       1           1       1         1        1          1         1
4802       0           0       0         0        0          0         0
4803       0           0       0         0        0          0         0
4804       0           0       0         0        0          0         0
4805       0           0       0         0        0          0         0
4806       1           1       1         1        1          1         1
4807       0           0       0         0        0          0         0
4808       0           0       0         0        0          0         0
4809       0           0       0         0        0          0         0
4810       0           0       0         0        0          0         0
4811       0           0       0         0        0          0         0
4812       0           0       0         0        0          0         0
4813       0           0       0         0        0          0         0
4814       0           0       0         0        0          0         0

[380955 rows x 7 columns]